# Auto-generated by generate_rx_filter_bands.py. Do not edit manually.
from __future__ import annotations
from dataclasses import dataclass
from enum import IntEnum

class DuplexorDirection(IntEnum):
    DD_UNKNOWN = -1
    DD_UPLINK = 0
    DD_DOWNLINK = 1
    DD_MAX_NO = 2

class BandFilter(IntEnum):
    BAND_FILTER_CDMA450 = 0
    BAND_FILTER_IDEN = 2
    BAND_FILTER_GSM850 = 4
    BAND_FILTER_EGSM900 = 6
    BAND_FILTER_DCS1800 = 8
    BAND_FILTER_PCS1900 = 10
    BAND_FILTER_3GBAND1 = 12
    BAND_FILTER_EMPTY = 14
    BAND_FILTER_LTE7 = 16
    BAND_FILTER_LTE20 = 18
    BAND_FILTER_LTE28 = 20
    BAND_FILTER_LTE12 = 22
    BAND_FILTER_LTE13 = 24
    BAND_FILTER_LTE17 = 26
    BAND_FILTER_LTE40 = 28
    BAND_FILTER_LTE38 = 30
    BAND_FILTER_LTE41 = 32
    BAND_FILTER_LTE25 = 34
    BAND_FILTER_LTE26 = 36
    BAND_FILTER_LTE71 = 38
    BAND_FILTER_N77 = 40
    BAND_FILTER_WIDE = 1000
    BAND_FILTER_ERROR = -1
    BAND_ID_NONE = 2147483647

class CalDataLookup(IntEnum):
    COVERT872CALDATALOOKUP_NO_LOOKUP = -1
    COVERT872CALDATALOOKUP_LTE_7 = 0
    COVERT872CALDATALOOKUP_DCS1800 = 1
    COVERT872CALDATALOOKUP_PCS1900 = 2
    COVERT872CALDATALOOKUP_UMTS_1 = 3
    COVERT872CALDATALOOKUP_GSM850 = 4
    COVERT872CALDATALOOKUP_EGSM900 = 5
    COVERT872CALDATALOOKUP_LTE_20 = 6
    COVERT872CALDATALOOKUP_WIDEBAND = 7
    COVERT872CALDATALOOKUP_LTE_12 = 8
    COVERT872CALDATALOOKUP_LTE_13 = 9
    COVERT872CALDATALOOKUP_LTE_28A = 10
    COVERT872CALDATALOOKUP_LTE_28B = 11
    COVERT872CALDATALOOKUP_LTE_40 = 12
    COVERT872CALDATALOOKUP_NO_OF_ENTRIES = 13

BOTH_DIR_MASK = 3
DOWNLINK_DIR_MASK = 2
EXTRA_DATA_FORREV_MASK = 1
EXTRA_DATA_SWAP_FOR_AND_REV_MASK = 2
UPLINK_DIR_MASK = 1

@dataclass
class FreqRange:
    low_dmhz: int
    high_dmhz: int

    @property
    def low_mhz(self) -> float: return self.low_dmhz / 10.0
    @property
    def high_mhz(self) -> float: return self.high_dmhz / 10.0
    @property
    def low_hz(self) -> int: return self.low_dmhz * 100_000
    @property
    def high_hz(self) -> int: return self.high_dmhz * 100_000

    def contains_dmhz(self, v: int) -> bool:
        if self.low_dmhz == 0 and self.high_dmhz == 0:
            return False
        return self.low_dmhz <= v <= self.high_dmhz

@dataclass
class RxFilterBand:
    uplink: FreqRange
    downlink: FreqRange
    direction_mask: int
    ladon_id: int
    band: BandFilter
    lte_band: int
    filter_no: int
    filters_per_band: int
    extra_data: int
    cal_lookup: CalDataLookup
    hardware_id: int

    def branch_for(self, direction: 'DuplexorDirection') -> FreqRange:
        if direction == DuplexorDirection.DD_UPLINK:
            return self.uplink
        elif direction == DuplexorDirection.DD_DOWNLINK:
            return self.downlink
        else:
            # Unknown: choose non-empty
            return self.uplink if self.uplink.high_dmhz else self.downlink

    def covers_freq_khz(self, freq_khz: int, bandwidth_khz: int, direction: 'DuplexorDirection') -> bool:
        # Convert kHz to dMHz (freq_khz / 100)
        low_edge_dmhz = (freq_khz - (bandwidth_khz + 1)//2 + 50) // 100
        high_edge_dmhz = (freq_khz + (bandwidth_khz + 1)//2 + 50) // 100
        rng = self.branch_for(direction)
        if rng.low_dmhz == 0 and rng.high_dmhz == 0:
            return False
        return rng.low_dmhz <= low_edge_dmhz and high_edge_dmhz <= rng.high_dmhz


RX_FILTER_BANDS: list[RxFilterBand] = [
    RxFilterBand(FreqRange(0, 0), FreqRange(0, 0), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_EMPTY, -1, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 0),
    RxFilterBand(FreqRange(100, 63000), FreqRange(0, 0), UPLINK_DIR_MASK, 1, BandFilter.BAND_FILTER_WIDE, 0, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_WIDEBAND, 1),
    RxFilterBand(FreqRange(4510, 4590), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_CDMA450, 31, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 2),
    RxFilterBand(FreqRange(0, 0), FreqRange(4600, 4670), DOWNLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_CDMA450, 31, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 3),
    RxFilterBand(FreqRange(8060, 8210), FreqRange(0, 0), UPLINK_DIR_MASK, 11, BandFilter.BAND_FILTER_IDEN, 27, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 4),
    RxFilterBand(FreqRange(0, 0), FreqRange(8510, 8660), DOWNLINK_DIR_MASK, 10, BandFilter.BAND_FILTER_IDEN, 27, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 5),
    RxFilterBand(FreqRange(8240, 8490), FreqRange(0, 0), UPLINK_DIR_MASK, 5, BandFilter.BAND_FILTER_GSM850, 5, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 6),
    RxFilterBand(FreqRange(0, 0), FreqRange(8690, 8940), DOWNLINK_DIR_MASK, 4, BandFilter.BAND_FILTER_GSM850, 5, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 7),
    RxFilterBand(FreqRange(8800, 9150), FreqRange(0, 0), UPLINK_DIR_MASK, 3, BandFilter.BAND_FILTER_EGSM900, 8, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 8),
    RxFilterBand(FreqRange(0, 0), FreqRange(9250, 9600), DOWNLINK_DIR_MASK, 2, BandFilter.BAND_FILTER_EGSM900, 8, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 9),
    RxFilterBand(FreqRange(17100, 17850), FreqRange(0, 0), UPLINK_DIR_MASK, 7, BandFilter.BAND_FILTER_DCS1800, 3, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 10),
    RxFilterBand(FreqRange(0, 0), FreqRange(18050, 18800), DOWNLINK_DIR_MASK, 6, BandFilter.BAND_FILTER_DCS1800, 3, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 11),
    RxFilterBand(FreqRange(18500, 19100), FreqRange(0, 0), UPLINK_DIR_MASK, 9, BandFilter.BAND_FILTER_PCS1900, 2, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 12),
    RxFilterBand(FreqRange(0, 0), FreqRange(19300, 19900), DOWNLINK_DIR_MASK, 8, BandFilter.BAND_FILTER_PCS1900, 2, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 13),
    RxFilterBand(FreqRange(19200, 19800), FreqRange(0, 0), UPLINK_DIR_MASK, 13, BandFilter.BAND_FILTER_3GBAND1, 1, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 14),
    RxFilterBand(FreqRange(0, 0), FreqRange(21100, 21700), DOWNLINK_DIR_MASK, 12, BandFilter.BAND_FILTER_3GBAND1, 1, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 15),
    RxFilterBand(FreqRange(8320, 8620), FreqRange(0, 0), UPLINK_DIR_MASK, 19, BandFilter.BAND_FILTER_LTE20, 20, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 16),
    RxFilterBand(FreqRange(0, 0), FreqRange(7910, 8210), DOWNLINK_DIR_MASK, 18, BandFilter.BAND_FILTER_LTE20, 20, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 17),
    RxFilterBand(FreqRange(25000, 25700), FreqRange(0, 0), UPLINK_DIR_MASK, 17, BandFilter.BAND_FILTER_LTE7, 7, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 18),
    RxFilterBand(FreqRange(0, 0), FreqRange(26200, 26900), DOWNLINK_DIR_MASK, 16, BandFilter.BAND_FILTER_LTE7, 7, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 19),
    RxFilterBand(FreqRange(8240, 8319), FreqRange(0, 0), UPLINK_DIR_MASK, 5, BandFilter.BAND_FILTER_GSM850, 5, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 20),
    RxFilterBand(FreqRange(25000, 25700), FreqRange(26200, 26900), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE7, 7, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_LTE_7, 21),
    RxFilterBand(FreqRange(17100, 17850), FreqRange(18050, 18800), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_DCS1800, 3, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_DCS1800, 22),
    RxFilterBand(FreqRange(18500, 19100), FreqRange(19300, 19900), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_PCS1900, 2, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_PCS1900, 23),
    RxFilterBand(FreqRange(19200, 20100), FreqRange(21100, 22000), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_3GBAND1, 1, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_UMTS_1, 24),
    RxFilterBand(FreqRange(8240, 8490), FreqRange(8690, 8940), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_GSM850, 5, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_GSM850, 25),
    RxFilterBand(FreqRange(8800, 9150), FreqRange(9250, 9600), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_EGSM900, 8, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_EGSM900, 26),
    RxFilterBand(FreqRange(8320, 8620), FreqRange(7910, 8210), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE20, 20, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_LTE_20, 27),
    RxFilterBand(FreqRange(7030, 7330), FreqRange(7580, 7880), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE28, 28, 1, 2, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 28),
    RxFilterBand(FreqRange(7180, 7480), FreqRange(7730, 8030), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE28, 28, 2, 2, 0, CalDataLookup.COVERT872CALDATALOOKUP_LTE_28B, 29),
    RxFilterBand(FreqRange(0, 0), FreqRange(8690, 8940), DOWNLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_GSM850, 5, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 30),
    RxFilterBand(FreqRange(8240, 8490), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_GSM850, 5, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 31),
    RxFilterBand(FreqRange(0, 0), FreqRange(9250, 9600), DOWNLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_EGSM900, 8, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 32),
    RxFilterBand(FreqRange(8800, 9150), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_EGSM900, 8, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 33),
    RxFilterBand(FreqRange(0, 0), FreqRange(18050, 18800), DOWNLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_DCS1800, 3, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 34),
    RxFilterBand(FreqRange(17100, 17850), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_DCS1800, 3, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 35),
    RxFilterBand(FreqRange(0, 0), FreqRange(19300, 19900), DOWNLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_PCS1900, 2, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 36),
    RxFilterBand(FreqRange(18500, 19100), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_PCS1900, 2, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 37),
    RxFilterBand(FreqRange(0, 0), FreqRange(21100, 22000), DOWNLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_3GBAND1, 1, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 38),
    RxFilterBand(FreqRange(19200, 20100), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_3GBAND1, 1, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 39),
    RxFilterBand(FreqRange(0, 0), FreqRange(26200, 26900), DOWNLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE7, 7, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 40),
    RxFilterBand(FreqRange(25000, 25700), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE7, 7, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 41),
    RxFilterBand(FreqRange(0, 0), FreqRange(7910, 8210), DOWNLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE20, 20, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 42),
    RxFilterBand(FreqRange(8320, 8620), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE20, 20, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 43),
    RxFilterBand(FreqRange(6980, 7160), FreqRange(7280, 7460), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE12, 12, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_LTE_12, 44),
    RxFilterBand(FreqRange(7770, 7870), FreqRange(7460, 7560), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE13, 13, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_LTE_13, 45),
    RxFilterBand(FreqRange(7040, 7160), FreqRange(7340, 7460), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE17, 17, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 46),
    RxFilterBand(FreqRange(25000, 25700), FreqRange(26200, 26900), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE7, 7, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 47),
    RxFilterBand(FreqRange(8320, 8620), FreqRange(7910, 8210), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE20, 20, 1, 1, EXTRA_DATA_FORREV_MASK, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 48),
    RxFilterBand(FreqRange(8240, 8490), FreqRange(8690, 8940), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_GSM850, 5, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 49),
    RxFilterBand(FreqRange(8800, 9150), FreqRange(9250, 9600), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_EGSM900, 8, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 50),
    RxFilterBand(FreqRange(17100, 17850), FreqRange(18050, 18800), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_DCS1800, 3, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 51),
    RxFilterBand(FreqRange(18500, 19100), FreqRange(19300, 19900), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_PCS1900, 2, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 52),
    RxFilterBand(FreqRange(19200, 20100), FreqRange(21100, 22000), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_3GBAND1, 1, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 53),
    RxFilterBand(FreqRange(7770, 7870), FreqRange(7460, 7560), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE13, 13, 1, 1, EXTRA_DATA_SWAP_FOR_AND_REV_MASK, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 54),
    RxFilterBand(FreqRange(23000, 24000), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE40, 40, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 55),
    RxFilterBand(FreqRange(23000, 24000), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE40, 40, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_LTE_40, 56),
    RxFilterBand(FreqRange(7030, 7330), FreqRange(7580, 7880), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE28, 28, 1, 2, EXTRA_DATA_SWAP_FOR_AND_REV_MASK, CalDataLookup.COVERT872CALDATALOOKUP_LTE_28A, 57),
    RxFilterBand(FreqRange(18500, 19200), FreqRange(19300, 19950), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE25, 25, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 58),
    RxFilterBand(FreqRange(8140, 8490), FreqRange(8590, 8940), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE26, 26, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 59),
    RxFilterBand(FreqRange(25700, 26200), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE38, 38, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 60),
    RxFilterBand(FreqRange(24960, 26900), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE41, 41, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 61),
    RxFilterBand(FreqRange(6630, 6980), FreqRange(6170, 6520), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE71, 71, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 62),
    RxFilterBand(FreqRange(33000, 42000), FreqRange(0, 0), UPLINK_DIR_MASK, 0, BandFilter.BAND_FILTER_N77, 77, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 63),
    RxFilterBand(FreqRange(8320, 8620), FreqRange(7910, 8210), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE20, 20, 1, 1, EXTRA_DATA_SWAP_FOR_AND_REV_MASK, CalDataLookup.COVERT872CALDATALOOKUP_LTE_20, 64),
    RxFilterBand(FreqRange(8320, 8620), FreqRange(7910, 8210), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE20, 20, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 65),
    RxFilterBand(FreqRange(7040, 7480), FreqRange(7580, 8030), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE28, 28, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 66),
    RxFilterBand(FreqRange(7040, 7480), FreqRange(7580, 8030), BOTH_DIR_MASK, 0, BandFilter.BAND_FILTER_LTE28, 28, 1, 1, 0, CalDataLookup.COVERT872CALDATALOOKUP_NO_LOOKUP, 67),
]

# Derived lookup dictionaries
BANDS_BY_FILTER: dict[BandFilter, list[RxFilterBand]] = {}
FILTERS_BY_LTE_BAND: dict[int, list[RxFilterBand]] = {}
FILTERS_BY_CAL_LOOKUP: dict[CalDataLookup, list[RxFilterBand]] = {}
for idx, f in enumerate(RX_FILTER_BANDS):
    BANDS_BY_FILTER.setdefault(f.band, []).append(f)
    FILTERS_BY_LTE_BAND.setdefault(f.lte_band, []).append(f)
    FILTERS_BY_CAL_LOOKUP.setdefault(f.cal_lookup, []).append(f)

WIDEBAND_INDEX = 1  # As per C constant

class SelectionResult(IntEnum):
    NOT_FOUND = -1


def _centre_offset(filter_band: RxFilterBand, freq_dmhz: int, direction: DuplexorDirection) -> int:
    rng = filter_band.branch_for(direction)
    centre = (rng.low_dmhz + rng.high_dmhz) // 2
    return abs(freq_dmhz - centre)


def select_filter(freq_khz: int, bandwidth_khz: int, direction: DuplexorDirection, fitted_ids: list[int] | None = None) -> int:
    # Select best filter index akin to PASSBAND_CENTRE_SEARCH logic.
    # If fitted_ids provided restrict search to those indices, else all.
    # Returns filter index or -1.
    if freq_khz >= 6_000_000:
        return SelectionResult.NOT_FOUND
    freq_dmhz = (freq_khz + 50) // 100
    low_edge_dmhz = (freq_khz - (bandwidth_khz + 1)//2 + 50) // 100
    high_edge_dmhz = (freq_khz + (bandwidth_khz + 1)//2 + 50) // 100

    indices = fitted_ids if fitted_ids is not None else list(range(len(RX_FILTER_BANDS)))
    wideband_present = False
    wideband_site = -1
    best_index = -1
    best_offset = 10**9

    for idx in indices:
        if idx < 0 or idx >= len(RX_FILTER_BANDS):
            continue
        f = RX_FILTER_BANDS[idx]
        if idx == WIDEBAND_INDEX:
            wideband_present = True
            wideband_site = idx
        # Check direction mask
        mask = UPLINK_DIR_MASK if direction == DuplexorDirection.DD_UPLINK else DOWNLINK_DIR_MASK
        if (f.direction_mask & mask) == 0:
            continue
        rng = f.branch_for(direction)
        if rng.low_dmhz == 0 or rng.high_dmhz == 0:
            continue
        if rng.low_dmhz <= low_edge_dmhz and high_edge_dmhz <= rng.high_dmhz:
            offset = _centre_offset(f, freq_dmhz, direction)
            if offset < best_offset and idx != WIDEBAND_INDEX:
                best_offset = offset
                best_index = idx
    if best_index == -1 and wideband_present:
        best_index = wideband_site
    return best_index

__all__ = ['DuplexorDirection','BandFilter','CalDataLookup','FreqRange','RxFilterBand',
           'RX_FILTER_BANDS','BANDS_BY_FILTER','FILTERS_BY_LTE_BAND','FILTERS_BY_CAL_LOOKUP',
           'select_filter','UPLINK_DIR_MASK','DOWNLINK_DIR_MASK','BOTH_DIR_MASK',
           'EXTRA_DATA_FORREV_MASK','EXTRA_DATA_SWAP_FOR_AND_REV_MASK']
