[cerberus]
identity = CERB_STATION_001

; # --- MySQL --------------
; [database]
; host=127.0.0.1
; port=3305
; username=root
; password=5m1thMy3r5
; database=cerberus

# --- PostgreSQL --------------
[database]
host=127.0.0.1
port=5432
username=cerberusUser
password=5m1thMy3r5
database=cerberus
